config/routes.rb
Pipegems::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
  end

  resources :rubygems do |rubygems|
    resources :rubygem_versions, :as => :versions
  end

  root :to => 'rubygems#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    if user
      can :create, :rubygems
      can :create, :rubygem_versions, user_id: user.id
    end
  end
end

app/models/gem_file.rb
class GemFile < ActiveRecord::Base
  belongs_to :rubygem_version
  mount_uploader :file, GemFileUploader
end

app/models/pipegem.rb
class Pipegem < ActiveRecord::Base
  has_many :versions, :dependent => :destroy

  strip_attributes :only => :name
  before_validation :name_delete_prefix

  validates :name, :presence   => true,
                   :uniqueness => { :case_sensitive => false }

  def name_delete_prefix
    self.name.try(:sub!, /\Apipe-/i, '')
  end
end

app/models/rubygem.rb
class Rubygem < ActiveRecord::Base
  belongs_to :user
  has_many :rubygem_versions

  validates :name, presence: true, uniqueness: true

  def lib_name
    "pipe-#{name.downcase}"
  end

  def class_name
    name.classify
  end
end

app/models/rubygem_file.rb
class RubygemFile < ActiveRecord::Base
  belongs_to :rubygem_version
  mount_uploader :file, RubygemFileUploader
end

app/models/rubygem_version.rb
require 'fileutils'
require 'erubis'

class RubygemVersion < ActiveRecord::Base
  belongs_to :rubygem
  has_many :rubygem_files, dependent: :destroy
  has_one :gem_file, dependent: :destroy

  delegate :user_id, to: :rubygem

  accepts_nested_attributes_for :rubygem_files, allow_destroy: true

  before_save :build!

  validates :version, presence: true, uniqueness: { scope: :rubygem_id }

  def build!
    assets = []

    gem_file = self.build_gem_file

    tmp_dir = "#{Dir.tmpdir}/#{rubygem.lib_name}/#{self.version}"
    lib_dir = "#{tmp_dir}/lib"
    js_dir  = "#{lib_dir}/assets/javascripts/"

    FileUtils.mkdir_p(js_dir)

    rubygem_files.each do |f|
      FileUtils.cp(f.file.path, "#{js_dir}/#{f.file_identifier}")
      assets << "lib/assets/javascripts/#{f.file_identifier}"
    end

    File.open "#{lib_dir}/#{rubygem.lib_name}.rb", 'w' do |f|
        f.write <<-eos
          require 'rails'

          module Pipe
            module #{rubygem.class_name}
              class Engine < ::Rails::Engine
              end
            end
          end
        eos
    end

    spec = Gem::Specification.new do |s|
      s.name     = rubygem.lib_name
      s.version  = self.version
      s.authors  = ['Sasha Koss']
      s.email    = 'koss@nocorp.me'
      s.homepage = 'http://github.com/kossnocorp/pipegems'

      s.summary     = 'Turn your .js to .gem'
      s.description = 'Turn your .js to .gem'
      s.files       = ["lib/#{rubygem.lib_name}.rb"] + assets

      s.add_dependency('rails', '~> 3.1.0')
    end

    File.open "#{tmp_dir}/#{rubygem.lib_name}.gemspec", 'w' do |f|
      f.write spec.to_ruby
    end

    Dir.chdir(tmp_dir)

    gem_file_path = `gem build #{rubygem.lib_name}.gemspec`.match(/File: (.+)$/)[1]

    gem_file.file = File.open(gem_file_path)
    gem_file.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  attr_accessible :nickname, :name, :email, :github_token, :password

  has_many :rubygems

  def self.find_or_create_by_oauth(access_token)
    data = access_token.info

    if user = User.where(email: data.email).first
      user
    else
      User.create! \
        nickname:     data.nickname,
        name:         data.name,
        email:        data.email,
        github_token: access_token.credentials.token,
        password:     Devise.friendly_token[0, 20]
    end
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
  has_many :version_files, :dependent => :destroy

  strip_attributes :only => :name
  before_validation :name_delete_prefix

  validates :name, :presence   => true,
                   :uniqueness => { :scope => :pipegem_id },
                   :format     => { :with => /\A[0-9]+(\.[0-9a-zA-Z]+)*\z/ }
                   # https://github.com/rubygems/rubygems/blob/master/lib/rubygems/version.rb#L150

  def name_delete_prefix
    self.name.try(:sub!, /\Av/i, '')
  end
end

app/models/version_file.rb
class VersionFile < ActiveRecord::Base
  mount_uploader :file, VersionFileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    sign_in_and_redirect \
      User.find_or_create_by_oauth( request.env['omniauth.auth'] ),
      event: :authentication
  end

  def passthru
    render file: "#{Rails.root}/public/404.html", status: 404, layout: false
  end
end

app/controllers/rubygem_versions_controller.rb
class RubygemVersionsController < InheritedResources::Base
  belongs_to :rubygem
  actions :index, :show, :new, :create
  load_and_authorize_resource

  def new
    3.times do
      @rubygem_version.rubygem_files.build
    end
    new!
  end

end

app/controllers/rubygems_controller.rb
class RubygemsController < InheritedResources::Base
  actions :index, :show, :new, :create
  load_and_authorize_resource

  protected

    def begin_of_association_chain
      params[:action] == 'create' ? current_user : nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rubygem_versions_helper.rb
module RubygemVersionsHelper
end

app/helpers/rubygems_helper.rb
module RubygemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pipegems</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless current_user %>
  <%= link_to 'Sign in with GitHub', user_omniauth_authorize_path(:github) %>
<% else %>
  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% end %>

<h2><%= link_to_unless_current 'PipeGems', root_path %></h2>

<%= yield %>

</body>
</html>

app/views/rubygem_versions/_form.html.erb
<%= form_for(@rubygem_version) do |f| %>
  <% if @rubygem_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubygem_version.errors.count, "error") %> prohibited this rubygem_version from being saved:</h2>

      <ul>
      <% @rubygem_version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>

  <%= f.fields_for :rubygem_files do |file_form| %>
    <div class="field">
      <%= file_form.label :file %><br />
      <%= file_form.file_field :file %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubygem_versions/index.html.erb
<h1>Listing rubygem_versions</h1>

<table>
  <tr>
    <th>Rubygem</th>
    <th>Version</th>
    <th></th>
  </tr>

<% @rubygem_versions.each do |rubygem_version| %>
  <tr>
    <td><%= rubygem_version.rubygem %></td>
    <td><%= rubygem_version.version %></td>
    <td><%= link_to 'Show', rubygem_version_path(@rubygem, rubygem_version) %></td>
  </tr>
<% end %>
</table>

<br />

<% if current_user == @rubygem.user %>
  <%= link_to 'New Rubygem version', new_rubygem_version_path(@rubygem) %>
<% end %>

app/views/rubygem_versions/new.html.erb
<h1>New rubygem_version</h1>

<%= render 'form' %>

<%= link_to 'Back', rubygem_versions_path %>

app/views/rubygem_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rubygem:</b>
  <%= @rubygem_version.rubygem %>
</p>

<p>
  <b>Version:</b>
  <%= @rubygem_version.version %>
</p>

<p>
  <b>Published:</b>
  <%= @rubygem_version.published %>
</p>

<%= link_to 'Edit', edit_rubygem_version_path(@rubygem_version) %> |
<%= link_to 'Back', rubygem_versions_path %>

app/views/rubygems/_form.html.erb
<%= form_for(@rubygem) do |f| %>
  <% if @rubygem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubygem.errors.count, "error") %> prohibited this rubygem from being saved:</h2>

      <ul>
      <% @rubygem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubygems/index.html.erb
<h1>Listing rubygems</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
  </tr>

<% @rubygems.each do |rubygem| %>
  <tr>
    <td><%= rubygem.name %></td>
    <td><%= rubygem.user.nickname %></td>
    <td><%= link_to 'Show', rubygem %></td>
  </tr>
<% end %>
</table>

<br />

<% if current_user %>
  <%= link_to 'New Rubygem', new_rubygem_path %>
<% end %>

app/views/rubygems/new.html.erb
<h1>New rubygem</h1>

<%= render 'form' %>

<%= link_to 'Back', rubygems_path %>

app/views/rubygems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rubygem.name %>
</p>

<p>
  <b><%= link_to 'Versions', rubygem_versions_path(@rubygem) %></b>
</p>

<%= link_to 'Back', rubygems_path %>